apiVersion: v1
kind: Namespace
metadata:
  name: test-app
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app1
  namespace: test-app
  labels:
    app: test-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app1
  template:
    metadata:
      labels:
        app: test-app1
    spec:
      containers:
      - name: nginx
        image: webserver-image:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-app1-svc
  namespace: test-app
  labels:
    app: test-app1
spec:
  type: NodePort
  selector:
    app: test-app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30010